version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_non_tags: true
configuration: Release
platform: Any CPU
shallow_clone: true
cache: packages -> **\packages.config
before_build:
- ps: nuget restore
build:
  publish_nuget: true
  parallel: true
  verbosity: minimal
artifacts:
- path: '**\WebDriverManager*.nupkg'
